export const bellClass = 'HeaderNav__btns'
export const musicClass = 'HeaderNav__audio'
export const leftLabelClass = 'left_label'
export const profileClass = 'TopNavBtn__profileLink'
export const mainLogoClass = 'main_logo'
